CREATE TABLE IF NOT EXISTS shopping_list (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    price decimal(12,2) not null,
    date_added timestamp DEFAULT now() not NULL,
    checked boolean DEFAULT 'false'
);

DROP TYPE IF EXISTS grocery;
CREATE TYPE grocery as ENUM(
    'Main',
    'Snack',
    'Lunch',
    'Breakfast'
);

ALTER TABLE shopping_list ADD COLUMN category grocery not null;


